---
- name: Ensure dependencies are installed.
  apt: pkg=curl state=installed

  # https://github.com/geerlingguy/ansible-role-jenkins/issues/47#issuecomment-212861640
- name: Fetch Jenkins LTS
  get_url:
      url: http://pkg.jenkins.io/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb 
      dest: /tmp/jenkins_{{ jenkins_version }}_all.deb

- name: Install Jenkins version
  apt: deb=/tmp/jenkins_{{ jenkins_version }}_all.deb
